require:
 - rubocop-minitest
 - rubocop-performance
 - rubocop-rake
 - standard
 - standard-performance

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Minitest/MultipleAssertions:
  Max: 5
