target :lib do
  signature "sig"
  signature "x-core/sig"
  signature "x-objects/sig"
  check "lib"
  check "x-core/lib"
  check "x-objects/lib"
  library "base64"
  library "cgi"
  library "forwardable"
  library "json"
  library "monitor"
  library "net-http"
  library "openssl"
  library "securerandom"
  library "time"
  library "tmpdir"
  library "uri"
  configure_code_diagnostics(Steep::Diagnostic::Ruby.strict)
end
