module X
  module Core
    VERSION: Gem::Version
  end

  class Authenticator
    AUTHENTICATION_HEADER: String

    def header: (Net::HTTPRequest? request) -> Hash[String, String]
    def inspect: () -> String
  end

  class BearerTokenAuthenticator < Authenticator
    attr_reader bearer_token: String
    def initialize: (bearer_token: String) -> void
    def header: (Net::HTTPRequest? request) -> Hash[String, String]
  end

  class OAuth2Authorization
    AUTHORIZATION_URL: String
    TOKEN_URL: String
    DEFAULT_SCOPES: Array[String]
    STATE_BYTES: Integer
    DEFAULT_ERROR_MESSAGE: String
    INVALID_CALLBACK_MESSAGE: String

    @pkce: SimpleOAuth::OAuth2::PKCE

    attr_reader client_id: String
    attr_reader client_secret: String?
    attr_reader redirect_uri: String
    attr_reader scopes: Array[String]
    attr_reader state: String
    attr_reader code_verifier: String
    attr_reader connection: Connection

    def initialize: (client_id: String, redirect_uri: String, ?client_secret: String?, ?scopes: Array[String], ?state: String, ?code_verifier: String, ?connection: Connection) -> void
    def inspect: () -> String
    def url: () -> String
    def credentials: (String | Hash[String | Symbol, String] callback) -> Hash[Symbol, String | Time | nil]
    def client: (String | Hash[String | Symbol, String] callback, **untyped options) -> Client

    private
    def oauth2_client: () -> SimpleOAuth::OAuth2::Client
    def query_of: (String | Hash[String | Symbol, String] callback) -> (String | Hash[String | Symbol, String])
    def credentials_from: (SimpleOAuth::OAuth2::Token token) -> Hash[Symbol, String | Time | nil]
  end

  class AuthorizationError < Error
    attr_reader code: String?
    attr_reader status: Integer?

    def self.from: (SimpleOAuth::OAuth2::Error error, String default_message) -> AuthorizationError
    def initialize: (String message, code: String?, ?status: Integer?) -> void
  end

  module TokenEndpoint
    extend TokenEndpoint

    def fetch: (SimpleOAuth::OAuth2::Request token_request, connection: Connection) -> SimpleOAuth::OAuth2::Token

    private
    def post: (SimpleOAuth::OAuth2::Request token_request) -> Net::HTTP::Post
  end

  class AppOnlyAuthenticator < Authenticator
    TOKEN_URL: String
    DEFAULT_ERROR_MESSAGE: String

    @bearer_token: String?
    @mutex: Thread::Mutex

    attr_reader api_key: String
    attr_reader api_key_secret: String
    attr_reader connection: Connection
    def initialize: (api_key: String, api_key_secret: String, ?bearer_token: String?, ?connection: Connection) -> void
    def header: (Net::HTTPRequest? request) -> Hash[String, String]
    def bearer_token: () -> String

    private
    def fetch_bearer_token: () -> String
    def token_request: () -> SimpleOAuth::OAuth2::Request
  end

  class OAuth1Authenticator < Authenticator
    OAUTH_VERSION: String
    OAUTH_SIGNATURE_METHOD: String
    FORM_CONTENT_TYPE: String

    attr_reader api_key: String
    attr_reader api_key_secret: String
    attr_reader access_token: String
    attr_reader access_token_secret: String
    def initialize: (api_key: String, api_key_secret: String, access_token: String, access_token_secret: String) -> void
    def header: (Net::HTTPRequest request) -> Hash[String, String]

    private
    def credentials: -> Hash[Symbol, String]
    def form_params: (Net::HTTPRequest request) -> Array[[String, String]]
    def form_body: (Net::HTTPRequest request) -> String
    def form_encoded?: (Net::HTTPRequest request) -> bool
  end

  class Error < StandardError
  end

  class ClientError < HTTPError
  end

  class BadGateway < ServerError
  end

  class BadRequest < ClientError
  end

  class Conflict < ClientError
  end

  class HTTPError < Error
    JSON_CONTENT_TYPE_REGEXP: Regexp

    attr_reader response : Net::HTTPResponse
    attr_reader code : String

    def initialize: (response: Net::HTTPResponse) -> void
    def status: () -> Integer

    private
    def error_message: (Net::HTTPResponse response) -> String
    def message_from_json_response: (Net::HTTPResponse response) -> String?
    def message_from_errors: (untyped errors) -> String?
    def message_from_problem: (Hash[String, untyped] body) -> String?
    def json?: (Net::HTTPResponse response) -> bool
  end

  class Forbidden < ClientError
  end

  class GatewayTimeout < ServerError
  end

  class Gone < ClientError
  end

  class InternalServerError < ServerError
  end

  class NetworkError < Error
  end

  class NotAcceptable < ClientError
  end

  class NotFound < ClientError
  end

  class PayloadTooLarge < ClientError
  end

  class ServerError < HTTPError
  end

  class ServiceUnavailable < ServerError
  end

  class TooManyRedirects < Error
  end

  class InvalidResponse < Error
    attr_reader response: Net::HTTPResponse

    def initialize: (response: Net::HTTPResponse) -> void
  end

  class TooManyRequests < ClientError
    @rate_limits: Array[RateLimit]

    def rate_limit: -> RateLimit?
    def rate_limits: -> Array[RateLimit]
    def reset_at: -> Time?
    def reset_in: -> Integer?
    def retry_after: -> Integer?
  end

  class Unauthorized < ClientError
  end

  class UnprocessableEntity < ClientError
  end

  class Connection
    DEFAULT_HOST: String
    DEFAULT_PORT: Integer
    DEFAULT_OPEN_TIMEOUT: Integer
    DEFAULT_READ_TIMEOUT: Integer
    DEFAULT_WRITE_TIMEOUT: Integer

    NETWORK_ERRORS: Array[(singleton(Errno::ECONNREFUSED) | singleton(Errno::ECONNRESET) | singleton(Errno::EHOSTUNREACH) | singleton(Errno::ENETUNREACH) | singleton(Errno::EPIPE) | singleton(Errno::ETIMEDOUT) | singleton(IOError) | singleton(Net::HTTPBadResponse) | singleton(Net::OpenTimeout) | singleton(Net::ReadTimeout) | singleton(Net::WriteTimeout) | singleton(OpenSSL::SSL::SSLError) | singleton(SocketError))]

    include ConnectionProxy

    attr_accessor open_timeout : Float | Integer
    attr_accessor read_timeout : Float | Integer
    attr_accessor write_timeout : Float | Integer
    attr_reader debug_output : IO?

    def initialize: (?open_timeout: Float | Integer, ?read_timeout: Float | Integer, ?write_timeout: Float | Integer, ?proxy_url: URI::Generic? | String?, ?debug_output: IO?) -> void
    def inspect: () -> String
    def perform: (request: Net::HTTPRequest) -> Net::HTTPResponse
    def perform_stream: (request: Net::HTTPRequest) { (Net::HTTPResponse) -> void } -> void

    @pool: ConnectionPool

    def debug_output=: (IO? debug_output) -> void
    def close: () -> void

    private
    def build_http_client: (?String host, ?Integer port) -> Net::HTTP
    def configure_http_client: (Net::HTTP http_client) -> Net::HTTP
    def configure_timeouts: (Net::HTTP http_client) -> Net::HTTP
  end

  module ConnectionProxy
    extend Forwardable

    @proxy_url: (URI::Generic | String)?
    @pool: ConnectionPool

    attr_reader proxy_url: (URI::Generic | String)?
    attr_reader proxy_uri: URI::Generic?
    attr_reader proxy_host : String?
    attr_reader proxy_port : Integer?

    def proxy_user: () -> String?
    def proxy_pass: () -> String?
    def proxy_url=: (URI::Generic? | String? proxy_url) -> void

    private
    def redacted_proxy_url: () -> String?
    def parse_proxy_url: (URI::Generic | String proxy_url) -> URI::Generic
    def redact: (URI::Generic | String proxy_url) -> String
  end

  class ConnectionPool
    MAX_IDLE: Integer

    @lock: Thread::Mutex
    @idle: Hash[[bool, String, Integer], Array[Net::HTTP]]
    @pid: Integer?

    def initialize: () -> void
    def with: [T] ([bool, String, Integer] key, ^() -> Net::HTTP open) { (Net::HTTP) -> T } -> T
    def clear: () -> void

    private
    def checkout: ([bool, String, Integer] key, ^() -> Net::HTTP open) -> [Hash[[bool, String, Integer], Array[Net::HTTP]], Net::HTTP]
    def checkin: ([bool, String, Integer] key, Net::HTTP http_client, Hash[[bool, String, Integer], Array[Net::HTTP]] pool) -> Array[Net::HTTP]?
    def forget_after_fork: () -> void
    def close: (Net::HTTP http_client) -> void
  end

  interface _BodyHook
    def call: (?String body) -> untyped
  end

  interface _ResponseHook
    def call: (Response response) -> untyped
  end

  class Response
    attr_reader http_method: Symbol
    attr_reader uri: URI::Generic
    attr_reader http_response: Net::HTTPResponse

    @body: String?

    def initialize: (Symbol http_method, URI::Generic uri, Net::HTTPResponse http_response, ?body: String?) -> void
    def body: () -> String?
    def status: () -> Integer
    def success?: () -> bool
    def rate_limits: () -> Array[RateLimit]
    def rate_limit: () -> RateLimit?
    def resource_counts: () -> Hash[String, Integer]
    def resource_count: () -> Integer

    private
    def parsed_body: () -> Hash[String, untyped]
  end

  class RateLimit
    RATE_LIMIT_TYPE: String
    APP_LIMIT_TYPE: String
    USER_LIMIT_TYPE: String
    TYPES: Array[String]

    attr_reader type: String
    attr_reader response: Net::HTTPResponse
    def self.reported?: (String type, Net::HTTPResponse response) -> bool
    def initialize: (type: String, response: Net::HTTPResponse) -> void
    def limit: -> Integer
    def remaining: -> Integer
    def exhausted?: -> bool
    def reset_at: -> Time
    def reset_in: -> Integer?
  end

  class RequestBuilder
    HTTP_METHODS: Hash[Symbol, (singleton(Net::HTTP::Get) | singleton(Net::HTTP::Post) | singleton(Net::HTTP::Put) | singleton(Net::HTTP::Delete))]
    DEFAULT_HEADERS: Hash[String, String]

    def initialize: (?content_type: String, ?user_agent: String) -> void
    def build: (http_method: Symbol, uri: URI::Generic, ?body: String?, ?headers: Hash[String, String], ?authenticator: Authenticator) -> (Net::HTTPRequest)

    private
    def create_request: (http_method: Symbol, uri: URI::Generic, body: String?) -> (Net::HTTPRequest)
    def add_authentication: (request: Net::HTTPRequest, authenticator: Authenticator) -> void
    def add_headers: (request: Net::HTTPRequest, headers: Hash[String, String]) -> void
    def escape_query_params: (URI::Generic uri) -> URI::Generic
  end

  class RateLimitHandler
    DEFAULT_MAX_RETRIES: Integer
    DEFAULT_MAX_WAIT: Integer
    UNREPORTED_RESET_WAIT: Integer

    attr_accessor max_rate_limit_retries: Integer
    attr_accessor max_rate_limit_wait: Integer
    def initialize: (?max_rate_limit_retries: Integer, ?max_rate_limit_wait: Integer) -> void
    def handle: [T] () { () -> T } -> T

    private
    def wait_before_retry: (TooManyRequests error, Integer retries) -> Integer
  end

  class ReconnectHandler
    DEFAULT_MAX_RECONNECTS: Float
    NETWORK_BACKOFF_STEP: Float
    MAX_NETWORK_BACKOFF: Integer
    HTTP_BACKOFF_START: Integer
    RATE_LIMIT_BACKOFF_START: Integer
    MAX_HTTP_BACKOFF: Integer
    RECONNECTABLE_ERRORS: Array[singleton(NetworkError) | singleton(ServerError) | singleton(Conflict) | singleton(TooManyRequests) | singleton(InvalidResponse)]

    ConsumerError: singleton(StandardError)

    type state = {reconnects: Integer}

    attr_accessor max_reconnects: Integer | Float
    def initialize: (?max_reconnects: Integer | Float) -> void
    def handle: (^(untyped) -> void consumer) { (^(untyped) -> void) -> void } -> nil

    private
    def cause_of: (StandardError error) -> StandardError
    def out_of_reconnects?: (StandardError? error, state state) -> bool
    def delivery_to: (^(untyped) -> void consumer, state state) -> ^(untyped) -> void
    def backoff: (StandardError error, Integer reconnects) -> (Float | Integer)
    def network_backoff: (Integer reconnects) -> (Float | Integer)
    def http_backoff: (Integer reconnects) -> Integer
    def rate_limit_backoff: (TooManyRequests error, Integer reconnects) -> Integer
  end

  class StreamingClient
    include RequestEncoding
    extend Forwardable

    DEFAULT_READ_TIMEOUT: Integer

    @connection: Connection
    @reconnect_handler: ReconnectHandler
    @request_builder: RequestBuilder
    @response_parser: ResponseParser
    @stream_parser: StreamParser

    attr_reader client: Client
    def initialize: (Client client, ?read_timeout: Float | Integer, ?max_reconnects: Integer | Float) -> void
    def inspect: () -> String
    def stream: (String endpoint, ?params: params?, ?headers: Hash[String, String], ?array_class: Class, ?object_class: Class) { (untyped) -> void } -> void
    def open_timeout: () -> (Float | Integer)
    def read_timeout: () -> (Float | Integer)
    def write_timeout: () -> (Float | Integer)
    def proxy_url: () -> (URI::Generic | String)?
    def debug_output: () -> IO?
    def open_timeout=: (Float | Integer timeout) -> (Float | Integer)
    def read_timeout=: (Float | Integer timeout) -> (Float | Integer)
    def write_timeout=: (Float | Integer timeout) -> (Float | Integer)
    def proxy_url=: (String? proxy_url) -> void
    def debug_output=: (IO? debug_output) -> IO?
    def max_reconnects: () -> (Integer | Float)
    def max_reconnects=: (Integer | Float max_reconnects) -> (Integer | Float)

    private
    def request_for: (URI::Generic uri, Hash[String, String] headers) -> Net::HTTPRequest
    def report: (URI::Generic uri, Net::HTTPResponse response, String? body) -> void
  end

  class RedirectHandler
    DEFAULT_MAX_REDIRECTS: Integer

    attr_reader connection: Connection
    attr_reader request_builder: RequestBuilder
    attr_reader max_redirects: Integer
    def initialize: (?connection: Connection, ?request_builder: RequestBuilder, ?max_redirects: Integer) -> void
    def handle: (response: Net::HTTPResponse, request: Net::HTTPRequest, ?headers: Hash[String, String], ?authenticator: Authenticator, ?redirect_count: Integer) -> Net::HTTPResponse

    private
    def build_new_uri: (Net::HTTPResponse response, URI::Generic uri) -> URI::Generic?
    def credentials_for: (URI::Generic from, URI::Generic to, Authenticator authenticator, Hash[String, String] headers) -> [Authenticator, Hash[String, String]]
    def same_origin?: (URI::Generic uri, URI::Generic other) -> bool
    def origin: (URI::Generic uri) -> [String?, String?, Integer?]
    def without_authorization: (Hash[String, String] headers) -> Hash[String, String]
    def build_request: (Net::HTTPRequest request, URI::Generic new_uri, Integer response_code, Hash[String, String] headers, Authenticator authenticator) -> Net::HTTPRequest
  end

  class ResponseParser
    STATUS_CLASS_ERRORS: Hash[Integer, singleton(ClientError) | singleton(ServerError)]
    ERROR_MAP: Hash[Integer, singleton(BadGateway) | singleton(BadRequest) | singleton(Conflict) | singleton(Forbidden) | singleton(GatewayTimeout) | singleton(Gone) | singleton(InternalServerError) | singleton(NotAcceptable) | singleton(NotFound) | singleton(PayloadTooLarge) | singleton(ServiceUnavailable) | singleton(TooManyRequests) | singleton(Unauthorized) | singleton(UnprocessableEntity)]

    def parse: (response: Net::HTTPResponse, ?array_class: Class?, ?object_class: untyped, ?client: Client?) -> untyped
    def decode: (String json, ?array_class: Class?, ?object_class: untyped, ?client: Client?) -> untyped

    private
    def error: (Net::HTTPResponse response) -> HTTPError
    def error_class: (Net::HTTPResponse response) -> (singleton(HTTPError) | singleton(BadGateway) | singleton(BadRequest) | singleton(Conflict) | singleton(Forbidden) | singleton(GatewayTimeout) | singleton(Gone) | singleton(InternalServerError) | singleton(NotAcceptable) | singleton(NotFound) | singleton(PayloadTooLarge) | singleton(ServiceUnavailable) | singleton(TooManyRequests) | singleton(Unauthorized) | singleton(UnprocessableEntity))
    def json?: (Net::HTTPResponse response) -> bool
  end

  class StreamParser
    LINE_DELIMITER: String

    def process: (response: Net::HTTPResponse, response_parser: ResponseParser, ?array_class: Class?, ?object_class: untyped, ?client: Client?, ?on_body: _BodyHook?) { (untyped) -> void } -> void

    private
    def raise_unless_successful: (response: Net::HTTPResponse, response_parser: ResponseParser, on_body: _BodyHook?) -> void
    def read_lines: (response: Net::HTTPResponse, decode: ^(String) -> untyped) { (untyped) -> void } -> void
    def process_buffer: (buffer: String, decode: ^(String) -> untyped) { (untyped) -> void } -> void
    def process_remaining: (buffer: String, decode: ^(String) -> untyped) { (untyped) -> void } -> void
    def yield_json: (line: String, decode: ^(String) -> untyped) { (untyped) -> void } -> void
  end


  class OAuth2Authenticator < Authenticator
    TOKEN_PATH: String
    TOKEN_HOST: String
    EXPIRATION_BUFFER: Integer
    DEFAULT_ERROR_MESSAGE: String

    attr_reader client_id: String
    attr_reader client_secret: String?
    attr_reader access_token: String
    attr_reader refresh_token: String
    attr_reader expires_at: Time?
    attr_reader connection: Connection
    attr_reader on_refresh: _TokenRefreshHook?
    @mutex: Thread::Mutex
    def initialize: (client_id: String, access_token: String, refresh_token: String, ?client_secret: String?, ?expires_at: Time?, ?connection: Connection, ?on_refresh: _TokenRefreshHook?) -> void
    def header: (Net::HTTPRequest? request) -> Hash[String, String]
    def inspect: () -> String
    def token_expired?: -> bool
    def refresh_token!: -> Hash[String, untyped]
    def refresh_rejected_token!: (String rejected_token) -> bool
    def retrying_rejected_token: [T] () { () -> T } -> T

    private
    def refresh: -> Hash[String, untyped]
    def report_refresh: -> void
    def oauth2_client: -> SimpleOAuth::OAuth2::Client
    def token_endpoint: -> String
    def update_tokens: (SimpleOAuth::OAuth2::Token token) -> void
  end

  interface _TokenRefreshHook
    def call: (OAuth2Authenticator authenticator) -> untyped
  end

  interface _CredentialHost
    def authenticator: () -> (Authenticator | BearerTokenAuthenticator | OAuth1Authenticator | OAuth2Authenticator)
    def copy: (**untyped options) -> Client
    def oauth2_authenticator_in_use: () -> OAuth2Authenticator?
    def oauth2_authenticator: () -> OAuth2Authenticator?
  end

  interface _SettingsHost
    def on_token_refresh: () -> _TokenRefreshHook?
  end

  module ClientSettings : _SettingsHost
    extend Forwardable
    @connection: Connection
    @request_builder: RequestBuilder
    @redirect_handler: RedirectHandler
    @rate_limit_handler: RateLimitHandler

    attr_reader base_url: String
    def base_url=: (String base_url) -> void
    attr_accessor default_array_class: singleton(Array)
    attr_accessor default_object_class: singleton(Hash)
    attr_accessor on_response: _ResponseHook?
    def open_timeout: () -> Integer
    def read_timeout: () -> Integer
    def write_timeout: () -> Integer
    def proxy_url: () -> String?
    def debug_output: () -> untyped
    def max_redirects: () -> Integer
    def max_rate_limit_retries: () -> Integer
    def max_rate_limit_wait: () -> Integer
    def open_timeout=: (Integer timeout) -> Integer
    def read_timeout=: (Integer timeout) -> Integer
    def write_timeout=: (Integer timeout) -> Integer
    def proxy_url=: (String? proxy_url) -> String?
    def debug_output=: (untyped output) -> untyped
    def max_redirects=: (Integer max_redirects) -> Integer
    def max_rate_limit_retries=: (Integer max_rate_limit_retries) -> Integer
    def max_rate_limit_wait=: (Integer max_rate_limit_wait) -> Integer

    private
    def initialize_settings: (base_url: String, default_array_class: singleton(Array), default_object_class: singleton(Hash), on_response: _ResponseHook?, max_redirects: Integer, max_rate_limit_retries: Integer, max_rate_limit_wait: Integer) -> void
    def settings: () -> Hash[Symbol, untyped]
    def report: (Symbol http_method, URI::Generic uri, Net::HTTPResponse response) -> void
  end

  module ClientCredentials : _CredentialHost
    @app_bearer_token: String?
    @connection: Connection

    def app_only: () -> (Client | self)
    @authenticator: Authenticator | BearerTokenAuthenticator | OAuth1Authenticator | OAuth2Authenticator

    attr_reader api_key: String?
    attr_reader api_key_secret: String?
    @access_token: String?
    @refresh_token: String?
    @expires_at: Time?
    def access_token: () -> String?
    def refresh_token: () -> String?
    def expires_at: () -> Time?
    attr_reader access_token_secret: String?
    attr_reader bearer_token: String?
    attr_reader client_id: String?
    attr_reader client_secret: String?
    def api_key=: (String api_key) -> void
    def api_key_secret=: (String api_key_secret) -> void
    def access_token=: (String access_token) -> void
    def access_token_secret=: (String access_token_secret) -> void
    def bearer_token=: (String bearer_token) -> void
    def client_id=: (String client_id) -> void
    def client_secret=: (String client_secret) -> void
    def refresh_token=: (String refresh_token) -> void
    def expires_at=: (Time? expires_at) -> void
    def update_credentials: (**String | Time | nil changes) -> void

    private
    def app_bearer_token: () -> String
    def fetched_app_bearer_token: () -> String
    def replace_credentials: (**String | Time | nil changes) -> void
    def credentials: () -> { api_key: String?, api_key_secret: String?, access_token: String?, access_token_secret: String?, bearer_token: String?, client_id: String?, client_secret: String?, refresh_token: String?, expires_at: Time? }
    def initialize_credentials: (api_key: String?, api_key_secret: String?, access_token: String?, access_token_secret: String?, bearer_token: String?, client_id: String?, client_secret: String?, refresh_token: String?, expires_at: Time?) -> void
    def initialize_authenticator: () -> (Authenticator | BearerTokenAuthenticator | OAuth1Authenticator | OAuth2Authenticator)
    def oauth1_authenticator: -> OAuth1Authenticator?
    def bearer_authenticator: -> BearerTokenAuthenticator?
    def app_only_authenticator: -> AppOnlyAuthenticator?
  end

  module RequestEncoding
    private
    def endpoint_with: (String endpoint, params? params) -> String
    def encode_body: (body? body, params? form) -> String?
  end

  type params = Hash[String | Symbol, untyped]
  type body = String | Hash[untyped, untyped]

  module CredentialValidator
    INCOMPLETE_CREDENTIALS: String
    INVALID_EXPIRES_AT: String
    extend CredentialValidator

    def validate_expires_at!: (untyped expires_at) -> void
    def validate!: (Authenticator authenticator, Hash[Symbol, String | Time | nil] credentials) -> void

    private
    def incomplete?: (Authenticator authenticator, Hash[Symbol, String | Time | nil] credentials) -> bool
  end

  class Client
    include ClientCredentials
    include ClientSettings
    include RequestEncoding

    DEFAULT_BASE_URL: String
    DEFAULT_ARRAY_CLASS: singleton(Array)
    DEFAULT_OBJECT_CLASS: singleton(Hash)
    FORM_CONTENT_TYPE: String
    @authenticator: Authenticator | BearerTokenAuthenticator | OAuth1Authenticator | OAuth2Authenticator
    @connection: Connection
    @request_builder: RequestBuilder
    @redirect_handler: RedirectHandler
    @rate_limit_handler: RateLimitHandler
    @response_parser: ResponseParser
    @client_id: String?
    @client_secret: String?
    @access_token: String?
    @refresh_token: String?
    @expires_at: Time?

    attr_accessor on_token_refresh: _TokenRefreshHook?
    attr_reader authenticator: Authenticator | BearerTokenAuthenticator | OAuth1Authenticator | OAuth2Authenticator
    def initialize: (?api_key: String?, ?api_key_secret: String?, ?access_token: String?, ?access_token_secret: String?, ?bearer_token: String?, ?client_id: String?, ?client_secret: String?, ?refresh_token: String?, ?expires_at: Time?, ?base_url: String, ?open_timeout: Integer, ?read_timeout: Integer, ?write_timeout: Integer, ?debug_output: untyped, ?proxy_url: String?, ?default_array_class: singleton(Array), ?default_object_class: singleton(Hash), ?max_redirects: Integer, ?max_rate_limit_retries: Integer, ?max_rate_limit_wait: Integer, ?on_response: _ResponseHook?, ?on_token_refresh: _TokenRefreshHook?) -> void
    def inspect: () -> String
    def copy: (**untyped options) -> Client
    def get: (String endpoint, ?params: params?, ?headers: Hash[String, String], ?array_class: Class, ?object_class: Class) -> untyped
    def post: (String endpoint, ?body? body, ?params: params?, ?form: params?, ?headers: Hash[String, String], ?array_class: Class, ?object_class: Class) -> untyped
    def put: (String endpoint, ?body? body, ?params: params?, ?form: params?, ?headers: Hash[String, String], ?array_class: Class, ?object_class: Class) -> untyped
    def delete: (String endpoint, ?params: params?, ?headers: Hash[String, String], ?array_class: Class, ?object_class: Class) -> untyped
    def streaming: (**untyped options) -> StreamingClient
    def share_authenticator: (Authenticator | BearerTokenAuthenticator | OAuth1Authenticator | OAuth2Authenticator other) -> void
    def oauth2_authenticator_in_use: () -> OAuth2Authenticator?
    def oauth2_authenticator: -> OAuth2Authenticator?

    private
    def oauth2_credentials_of: (OAuth2Authenticator authenticator) -> [String, String?, String, String, Time?]
    def refreshing_rejected_token: [T] () { () -> T } -> T
    def perform: (:delete | :get | :post | :put http_method, URI::Generic uri, body: String?, headers: Hash[String, String], array_class: Class, object_class: Class) -> untyped
    def execute_request: (:delete | :get | :post | :put http_method, String endpoint, ?body: body?, ?params: params?, ?form: params?, ?headers: Hash[String, String], ?array_class: Class, ?object_class: Class) -> untyped
  end
end
