# Type checks x-media against the signatures that x-core ships
target :lib do
  signature "sig"
  signature "../x-core/sig/x-core.rbs"
  check "lib"
  library "base64"
  library "cgi"
  library "forwardable"
  library "json"
  library "net-http"
  library "openssl"
  library "securerandom"
  library "tmpdir"
  library "uri"
  configure_code_diagnostics(Steep::Diagnostic::Ruby.strict)
end
