# frozen_string_literal: true

# Type checks x-uploader against the signatures that x-core ships
target :lib do
  signature "sig"
  signature "../x-core/sig/x-core.rbs"
  check "lib"
  library "forwardable"
  library "json"
  library "monitor"
  library "net-http"
  library "openssl"
  library "securerandom"
  library "simple_oauth"
  library "tmpdir"
  library "uri"
  library "zlib"
  configure_code_diagnostics(Steep::Diagnostic::Ruby.strict)
end
