target :lib do
  signature "sig"
  check "lib"
  library "forwardable"
  library "json"
  library "net-http"
  library "openssl"
  library "securerandom"
  library "simple_oauth"
  library "uri"
  configure_code_diagnostics(Steep::Diagnostic::Ruby.strict)
end
