source "https://rubygems.org"

# Specify the gem's dependencies in x-objects.gemspec
gemspec

gem "minitest", ">= 6"
gem "minitest-mock", ">= 5.27"
gem "mutant-minitest", ">= 0.14.1"
gem "rake", ">= 13.0.6"
gem "simplecov", ">= 1"
gem "steep", ">= 1.10"
gem "yard", ">= 0.9"
gem "yardstick", ">= 0.9"
