target :lib do
  signature "sig"
  check "lib"
  library "forwardable"
  library "json"
  library "monitor"
  library "time"
  library "uri"
  configure_code_diagnostics(Steep::Diagnostic::Ruby.strict)
end
