name: linter
on:
  push:
    paths:
      - "**.rb"
      - "**/Gemfile"
      - "**/Rakefile"
      - "**/Steepfile"
      - "**.gemspec"
      - "bin/**"
      - ".rubocop.yml"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**.rb"
      - "**/Gemfile"
      - "**/Rakefile"
      - "**/Steepfile"
      - "**.gemspec"
      - "bin/**"
      - ".rubocop.yml"
      - ".github/workflows/lint.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
        bundler-cache: true
    - run: bundle exec rake lint
