name: x-media
on:
  push:
    paths:
      - "x-media/**"
      - "!x-media/**.md"
      - "x-core/lib/**"
      - "x-core/sig/*.rbs"
      - "x-core/x-core.gemspec"
      - ".github/workflows/x-media.yml"
  pull_request:
    paths:
      - "x-media/**"
      - "!x-media/**.md"
      - "x-core/lib/**"
      - "x-core/sig/*.rbs"
      - "x-core/x-core.gemspec"
      - ".github/workflows/x-media.yml"
defaults:
  run:
    working-directory: x-media
jobs:
  test:
    strategy:
      matrix:
        ruby: ["3.2", "3.3", "3.4", "4.0"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        working-directory: x-media
    - run: bundle exec rake test
  mutant:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4"
        bundler-cache: true
        working-directory: x-media
    - run: bundle exec rake mutant
  steep:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4"
        bundler-cache: true
        working-directory: x-media
    - run: bundle exec rake steep
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4"
        bundler-cache: true
        working-directory: x-media
    - run: bundle exec rake yardstick
